# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dev-channel.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dev-channel.yml down`
version: "3.5"
services:
  chrome:
    platform: linux/amd64
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium_grid

  edge:
    platform: linux/amd64
    image: selenium/node-edge
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium_grid

  firefox:
    platform: linux/amd64
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium_grid

  selenium-hub:
    platform: linux/amd64
    image: selenium/hub:latest
    container_name: selenium-hub
    networks:
      - selenium_grid
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  selenium_grid:
    driver: bridge
    name: selenium_grid_custom_network

volumes:
  selenium_volume:
    name: selenium_volume_grid
    driver: local