version: '3.4'

services:
  seleniumpython:
    image: test_image
    container_name: test_container
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - selenium-hub_selenium_grid
#    command: ["pytest"]

networks:
  selenium-hub_selenium_grid:
    external:
      name: selenium_grid_custom_network
