version: '3.5'

services:
  seleniumpython:
    image: test_image
    container_name: test_container
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - selenium-hub_selenium_grid
    volumes:
      - selenium_volume:/app
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    command: ["pytest -n ${Test_Count}"]

networks:
  selenium-hub_selenium_grid:
    external: true
    name: selenium_grid_custom_network

volumes:
  selenium_volume:
    external: true
    name: selenium_volume
